config/routes.rb
Rails.application.routes.draw do

  get '/issue_book', to: 'issued_books#new'
  post '/issue_book', to: 'issued_books#create'
  get '/issued_books', to: 'issued_books#index'

  get '/books/new', to: 'books#new'

  get '/books/show', to: 'books#index'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  get '/addbook', to: 'books#new'
  post '/addbook', to: 'books#create'

  resources :users
  resources :books
  resources :issued_books

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  has_many :issued_books
  has_many :users, through: :issued_books
  validates :isbn, presence: true, length: { is: 13},
            uniqueness: {case_sensitive: false}
  validates :name, presence: true,length: { maximum: 100 }
  validates :author, presence: true,length: { maximum: 50 }
  validates :total_copies, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1}
  validates :available_copies, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0}

end

app/models/issued_book.rb
class IssuedBook < ApplicationRecord
  belongs_to :book
  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  has_many :issued_books
  has_many :books, through: :issued_books
  before_save { email.downcase! }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX},
            uniqueness: { case_sensitive: false }
  validates :user_type, presence: true, length: { maximum: 1 }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  include ApplicationHelper

  #it makes sure that that the user is logged in as admin before accessing library
  before_action :require_login_as_admin
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
    if @books.empty?      #if there are no books
      flash[:danger] = "There are no books in the lirary!! You can add a book here!"
      redirect_to addbook_path
    end
  end

  def new
    @book = Book.new
  end

  def show
    @book = Book.find_by(id: params[:id])
    if @book.nil?         #if the book is not present in the database
      flash[:danger] = "There is no such book in the lirary"
      redirect_to books_show_path
    end
  end

  def create
    @book = Book.new(book_params)
    @book.update_attribute(:available_copies, params[:book][:total_copies])  #initially the available copies are equal to the number of total copies
    if @book.save
      flash[:success] = "The book has been successfully added to lirary"
      redirect_to @book
    else    #The error will be displayed. We can be more specific like based on error we can ask if more copies need to be added.
      render 'new'
    end
  end

  #filtering data
  private
  def book_params
    params.require(:book).permit(:isbn, :name, :author, :total_copies)
  end
end

app/controllers/issued_books_controller.rb
class IssuedBooksController < ApplicationController

  def new
    @issued_book = IssuedBook.new
  end

  def show

  end

  def index
    @issued_books = IssuedBook.all
    if @issued_books.empty?
      flash[:danger] = "No books issued yet!! You can issue a book here"
      redirect_to issue_book_path
    end
  end

  def create

    #find the user and the book by the IDs provided
    book = Book.all.find_by(id: params[:issued_book][:book_id])
    user = User.all.find_by(id: params[:issued_book][:user_id])

    #checking if the user and the book exit
    if book.nil?
      flash[:danger] = 'Book not found!!'
      redirect_to issue_book_path
    elsif user.nil?
      flash[:danger] = 'User not found!!'
      redirect_to issue_book_path
    elsif book.available_copies < 1       #check the availability before proceeding. This code can be shifted to model with the help custom validations
      flash[:danger] = 'No copy of this book is available right now!!'
      redirect_to issue_book_path
    else          #save the book finally
      @issued_book = IssuedBook.new(book_id: params[:issued_book][:book_id],
                                    user_id: params[:issued_book][:user_id],
                                    issue_date: Date.today, exp_return_date: Date.today+1.month)
      begin
        #A transaction is used while saving the details because two models need to be updated simultaneously:
        #1. the book's availability has to be decreased by one and
        #2. the issue detail is to be saved otherwise rollback
        ActiveRecord::Base.transaction do
          @issued_book.save!
          book.update_attribute( :available_copies, book.available_copies-1 )
          book.save!
        end
        flash[:success] = "The book has been successfully issued to #{user.name}"
        redirect_to @issued_book
      rescue => e     #handle the error if transaction failed.
        flash[:danger] = "The book could not be issued.. please try again!!"
        render 'new'
      end
    end
  end
end

app/controllers/sessions_controller.rb
#the sessions class for creating and destroying session
class SessionsController < ApplicationController
  skip_before_action :require_login_as_admin, only: [:new,:create]
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      if user.user_type == "A"
        log_in user
        flash[:success] = "Welcome #{user.name}"
        redirect_to user
      else
        flash.now[:danger] = 'Sorry...but only the admins can login currently!!'
        render 'new'
      end
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end

  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
#This controller contains static pages used across the app.
class StaticPagesController < ApplicationController
  skip_before_action :require_login_as_admin
  def home
    if logged_in?
      redirect_to current_user
    end
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  #This function will facilitate the title
	def full_title(page_title = '')
    base_title = "Library"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end

  #the method below is put here because it will then be available across all the controllers to ensure that user is logged in before proceeding
  def require_login_as_admin
    if current_user == nil
      flash[:danger] = 'You have not logged in yet, login to see this page!!'
      redirect_to login_path
      return false
    elsif current_user.user_type != "A"
      flash[:danger] = 'You are not authorized to view this page!!'
      redirect_to root_path
      return false
    else
      return true
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/issued_books_helper.rb
module IssuedBooksHelper

end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end


  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/index.html.erb
<div class="jumbotron">
  <h1 class="center">All Books in library</h1>
  <table class="table table-bordered table-hover table-responsive">
    <thead>
    <tr>
      <th>Isbn</th>
      <th>Name</th>
      <th>Author</th>
      <th>Available Copies</th>
      <th>Total Copies</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @books.each do |book| %>
        <tr>
          <th scope="row"><%= book.isbn %></th>
          <td><%= book.name %></td>
          <td><%= book.author %></td>
          <td><%= book.available_copies %></td>
          <td><%= book.total_copies %></td>
          <td><%= link_to 'Show', book %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/books/new.html.erb
<% provide(:title, 'Add new book') %>
<h1>Add a new book:</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@book) do |f| %>
        <%= render 'shared/error_messages' %>

        <%= f.label :isbn, "ISBN" %>
        <%= f.text_field :isbn, class: 'form-control' %>

        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :author %>
        <%= f.text_field :author, class: 'form-control' %>

        <%= f.label :total_copies, "Copies" %>
        <%= f.text_field :total_copies, class: 'form-control' %>

        <%= f.submit "Add the book", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/books/show.html.erb
<h1><%= @book.name %></h1>
<div class="jumbotron row">
  <h3 class="center h3">Book details:</h3>
  <table class="table center table-bordered table-hover table-striped col-4">
    <tbody>
        <tr>
          <th scope="row">ISBN:</th>
          <td><%= @book.isbn %></td>
        </tr>
        <tr>
          <th scope="row">Title:</th>
          <td><%= @book.name %></td>
        </tr>
        <tr>
          <th scope="row">Author:</th>
          <td><%= @book.author %></td>
        </tr>
        <tr>
          <th scope="row">Available copies:</th>
          <td><%= @book.available_copies %></td>
        </tr>
        <tr>
          <th scope="row">Total copies:</th>
          <td><%= @book.total_copies %></td>
        </tr>
    </tbody>
  </table>
</div>

app/views/issued_books/index.html.erb
<div class="jumbotron">
  <h1 class="center">Issued books</h1>
  <table class="table table-bordered table-hover table-responsive">
    <thead>
    <tr>
      <th>Isbn</th>
      <th>Name</th>
      <th>Author</th>
      <th>Available Copies</th>
      <th>User name</th>
      <th>User Email</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @issued_books.each do |book| %>
        <tr>
          <th scope="row"><%= book.book.isbn %></th>
          <td><%= book.book.name %></td>
          <td><%= book.book.author %></td>
          <td><%= book.book.available_copies %></td>
          <td><%= book.user.name %></td>
          <td><%= book.user.email %></td>
          <td><%= link_to 'Show', book.book %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/issued_books/new.html.erb
<% provide(:title, 'Issue a book') %>
<h1>Issue a book:</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@issued_book) do |f| %>
        <%= render 'shared/error_messages' %>

        <%= f.label :user_id, "User ID:" %>
        <%= f.text_field :user_id, class: 'form-control' %>

        <%= f.label :book_id, "Book ID:" %>
        <%= f.text_field :book_id, class: 'form-control' %>

        <%= f.submit "Check and issue the book", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/issued_books/show.html.erb
<h1>IssuedBooks#show</h1>
<p>Find me in app/views/issued_books/show.html.erb</p>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    A <a href="https://snkshukla-lib.herokuapp.com">library management application </a>
    by <a href="http://www.michaelhartl.com/">Shubham Shukla</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Library Management", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Books <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Show all books", books_show_path %></li>
              <li><%= link_to "Show available books", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Add a new book", addbook_path %>
                <%= link_to "Issue a book", issue_book_path %>
              </li>
            </ul>
          </li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Add new user", '#' %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Login", login_path%></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
			<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
			</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
	
	<title><%= full_title(yield(:title)) %></title>
    
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  
  </head>

	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<% flash.each do |message_type, message| %>
				<%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
			<% end %>
			<%= yield %>
			<%= render 'layouts/footer' %>
		</div>
    <div class="container">
    <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @book && @book.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@book.errors.count, "error") %>.
    </div>
    <ul>
    <% @book.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  This is a library web application where one can browse books and their availability.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
  This page is under construction! You will soon be able to contact us.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  This page is under construction! You will soon be able to reach us.
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Library</h1>
  <%= link_to "Get Started!", login_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/users/index.html.erb
<div class="jumbotron">
  <h1 class="center">All Users of library</h1>
  <table class="table table-bordered table-hover table-responsive">
    <thead>
    <tr>
      <th>User ID</th>
      <th>Name</th>
      <th>Email</th>
      <th>User type</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @users.each do |user| %>
        <tr>
          <td><%= user.id %></td>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><% if user.user_type == "A" %>
                Admin
            <% elsif user.user_type == "N" %>
                Normal
            <% else %>
                Other
            <% end %></td>
          <td><%= link_to 'Show', user %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<div class="jumbotron row">
  <h3 class="center h3">User details:</h3>
  <table class="table center table-bordered table-hover table-striped col-md-8">
    <tbody>
    <tr>
      <th scope="row" class="col-md-4">User ID</th>
      <td class="col-md-4"><%= @user.id %></td>
    </tr>
    <tr>
      <th scope="row">Name:</th>
      <td><%= @user.name %></td>
    </tr>
    <tr>
      <th scope="row">email:</th>
      <td><%= @user.email %></td>
    </tr>
    <tr>
      <th scope="row">User type:</th>
      <td><%= @user.user_type %></td>
    </tr>
    </tbody>
  </table>
</div>